### ISSUE TITLE
downloader thinks it's done too early

### ISSUE THREAD

**Issue by bleedscarlet** [felipegiacomozzi/the-trove-downloader#13]
Trying to download a large number of folders and it seems to just quit, this is one of the folders I'm trying to download: /Assets/By%20Artist%20or%20Source/Gabriel%20Pickard/ and it thinks its done after hitting 60-80 folders or so, all folders with a large amount of subfolders seem to just quit similarly. Restarting in the same directory scans already downloaded files correctly, but still can't seem to get past it somehow. Windows x64.

It's not erroring, it thinks it finished somehow.

also tried to manually have it ignore the folders by typing them in, it seemed to check the folders anyway.

**Comment by bleedscarlet** [comment]
I should clarify, it's not erroring, it thinks it finished somehow.

**Comment by PriamX** [comment]
I have the same symptoms, Using v1.0.8 on Linux. It's never in the same place, Sometimes quits while skipping (before it hits files it needs to download). But mostly it seems ot be on folders with deep subdirectories. 

Edit: No error file is generated.

**Comment by bleedscarlet** [comment]
I ended up going back to wget, and figured something out that worked. I've only done single artist folders "by artist or by source" but many of those have hundreds of subfolders and this appeared to work:

`wget -r -np -k --user-agent="_" -A jpeg,jpg,bmp,gif,png "index.html*" https://url_here.is/`

**Comment by MoltenMarmot** [comment]
Hi, 

I'm also having this problem, where when I tell the program to download all of the files, it skips over most of the files and then prints, "Press any key to close this window".

I haven't been able to get it download specific folders.

**Comment by Meketh74** [comment]
Hi,

based on my experience it might be a server side issue with trove.is at some point in the downloading process. 

When I combine OpenDirectoryDownloader and wget it also runs for a while and then stops/ends. Re-running the same wget sequence then passes and continues but stops at another point, so it does not seem to be an issue with a specific file.
Wget I use is:
wget -P X:\TargetDirectory\ -x -N -i "Scan from OpenDirectoryDownloader.txt" -l 0 -t50

Maybe building in a loop in the trove downloader tool for files that are not downloaded might be a solution to fix the problem. Alternatively skipping files that are not downloaded, logging which were not downloaded and returning to them later on could help. Unfortunately V1.0.8 of this tool does currently not provide a log file at all.

@felipegiacomozzi: Happy to help with debugging if you provide some guidance what you need or which info would be helpful

Best and stay healthy
M.

**Comment by felipegiacomozzi** [comment]
I just released a new version: https://github.com/felipegiacomozzi/the-trove-downloader/releases/tag/1.0.10

I found some weird spacer elements that would break the program.
Could you try it out? Thanks!

**Comment by bleedscarlet** [comment]
Not sure if the issue is related or even similar, but I tried it again and had an actual error this time:

```
[15:18:01] Checking Item SF/
[15:18:01] Loading Page https://thetrove.is/Assets/By%20Artist%20or%20Source//0-hr//SF/
[15:18:01] Error: Object reference not set to an instance of an object.
[15:18:01] 

 

-----------------------------------------------------------------------------------
[15:18:01] For help in solving this problem, please send the log file generated in this folder (the-trove-downloader.log)
[15:18:01] to the Issues page on GitHub (https://github.com/felipegiacomozzi/the-trove-downloader/issues)
[15:18:01] OS Description: Microsoft Windows 10.0.18363
[15:18:01] OS Architecture: X64
[15:18:01] TheTroveDownloader Version: 1.0.10
[15:18:01] IgnoredNames: Parent directory/, ?one, .DS_Store
[15:18:01] OnlyIncludedNames: 
[15:18:01] IgnoredTypes: .html
[15:18:01] _basePath: D:/######/TheTrove/
[15:18:01] _parallel: 40
[15:18:01] _theTroveUrl: https://thetrove.is/Assets/By%20Artist%20or%20Source/
[15:18:01] ---------------------------------- LAST DOWNLOAD ERROR --------------------------------------
[15:18:01] 
[15:18:01] ---------------------------------- MAIN EXCEPTION -------------------------------------------
[15:18:01] System.NullReferenceException
Message : Object reference not set to an instance of an object.
StackTrace :    at TheTroveDownloader.TheTroveDownloader.LoadPage(String baseUrl, String basePath)
   at TheTroveDownloader.TheTroveDownloader.HandlePageItems(String baseUrl, String basePath, List`1 items)
   at TheTroveDownloader.TheTroveDownloader.LoadPage(String baseUrl, String basePath)
   at TheTroveDownloader.TheTroveDownloader.HandlePageItems(String baseUrl, String basePath, List`1 items)
   at TheTroveDownloader.TheTroveDownloader.LoadPage(String baseUrl, String basePath)
   at TheTroveDownloader.TheTroveDownloader.StartAsync(CancellationToken cancellationToken)

[15:18:02] 

 

Press any key to close this window
[15:18:02] Application started. Press Ctrl+C to shut down.
[15:18:02] Hosting environment: Production
[15:18:02] Content root path: C:\Users\########\AppData\Local\Temp\.net\TheTroveDownloader\gkgfc5bs.sqi\
```

**Comment by felipegiacomozzi** [comment]
Hello @bleedscarlet ,
Unfortunately this SF link goes to a different type of page: https://thetrove.is/Assets/By%20Artist%20or%20Source/0-hr/SF/
That's why it breaks.
Please put the SF folder as ignored on your download list.

**Comment by bleedscarlet** [comment]
Couldn't figure out how to ignore SF, as a folder or as a filename, but I picked the couple of folders that I wanted to grab from and it appears to be downloading everything as expected, not terminating unexpectedly or throwing any errors yet. Thanks felipe!!!
